# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vaughan Schmidt
email: vaughan.schmidt@gmail.com
author: Vaughan Schmidt
copyright: Copyright © 2020
description: >- # this means to ignore newlines until "baseurl:"
    Welcome to my personal blog... these are probably not the droids you are looking for,
    but welcome! This is a space I use to organize my thoughts, track projects and ideas,
    and discuss topics of interest. Usually (but not always) about software development
    topics.
baseurl: "/cvschmidt" # the subpath of your site, e.g. /blog
url: "http://vschmidt94.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: vschmidt94

# defaults
defaults:
    home:
        heading: "code.mechanics"
        subheading: "The nuts and bolts of software development."
        banner: "header.jpg"

# Build settings
theme: jekyll-theme-yat
plugins:
  - jekyll-feed

header_pages:
    - about.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
